# Generated by Django 5.2.13 on 2026-04-13 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=120)),
                ('frequency', models.CharField(max_length=120)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_orders', to='patients.patient')),
            ],
            options={
                'db_table': 'medication_orders',
            },
        ),
    ]
